services:
  # 1. База данни
  database:
    image: mariadb:10.6
    container_name: wp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - wp-network

  # 2. WordPress (PHP-FPM)
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wp_app
    restart: unless-stopped
    depends_on:
      - database
      - redis
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./wp_data:/var/www/html
        - ./conf/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      # Свързваме custom php конфигурация ако се наложи
    networks:
      - wp-network

  # 3. Web Server (Nginx)
  nginx:
    image: nginx:alpine
    container_name: wp_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wp_data:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      - wordpress
    networks:
      - wp-network

  # 4. Redis (Кеширане - прави сайта много по-бърз)
  redis:
    image: redis:alpine
    container_name: wp_redis
    restart: unless-stopped
    networks:
      - wp-network

  # 5. PhpMyAdmin (Лесно управление на базата)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_pma
    restart: unless-stopped
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8080:80" # Достъпен на порт 8080
    networks:
      - wp-network

  # 6. Monitoring (Node Exporter - както е в условието)
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    ports:
      - "9100:9100"
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge
